version: '3'

services:

  server:
    # Allows colored text.
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: server
    depends_on:
      - db
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://postgres@db:5432/dev
    ports:
      - "8080:8080"
      - "127.0.0.1:9229:9229" # V8 inspector
      - "127.0.0.1:9230:9230" # V8 inspector
    volumes:
      - npm:/home/.npm/_cacache/
      - ./:/usr/src/app

    # Starts the server & watches for changes (with debugger support)
    command: nodemon --inspect=0.0.0.0:9229 src/server.js

  db:
    image: mongo:3.6
    volumes:
      - db:/data/db

volumes:
  npm:
  db: